### ISSUE TITLE
install-jq.sh missing dependency pipenv

### ISSUE THREAD

**Issue by glaudiston** [cup/hearth#29]
I'm trying to build your static linked jq and figure out that it need the pipenv, I do suggest you to add a comment or a command to install it. like:
    # The hearth/scripts/install-jq.sh miss the pip and pipenv dependency
    pip install pipenv

**Comment by cup** [comment]
1. it doesnt need pipenv

2. script is not longer called `install-jq.sh` and hasnt been for several years

3. script isnt even at this repo anymore its here
https://github.com/cup/cerise

4. and in fact its not even there anymore - as i havent used JQ lately - here is last tree:

https://github.com/cup/cerise/tree/5575ff8/mingw-w64-x86-64/jq

i am closing this for now - if you have further issue let me know and i can reopen
